@startuml Selecionar mídia
actor Usuario
actor Sistema 
(Usuario) --> (Selecionar midia)
(Selecionar midia) <.. (Assistir) :Extends
(Assistir) ..> (Play/pause) :Include
(Assistir) ..> (Manter estado) :Include

(Selecionar midia) <.. (Adicionar à lista) :Extends
(Selecionar midia) <.. (Classificar) :Extends
(Selecionar midia) <.. (Remover da fileira) :Extends
(Selecionar midia) <.. (Ver informações) :Extends

(Sistema) --> (Carregar informações)
(Sistema) --> (Salvar alterações)

(Selecionar midia) ..> (Salvar alterações) : Include
(Ver informações) ..> (Carregar informações) :Include

@enduml