@startuml cadastro
actor Usuario
Usuario -- (Realizar Cadastro)
(Realizar Cadastro) <.. (Realizar login) : extends
(Realizar Cadastro) ..> (Informar e-mail) : include
(Realizar Cadastro) ..> (Informar senha) : include
(Realizar Cadastro) ..> (Escolher plano) : include
(Escolher plano) ..> (Forma de pagamento) : include
(Realizar Cadastro) .> (Validar cadastro) : include
(Validar cadastro) ..> (Emitir termos de uso) :include
@enduml