@startuml selecionar midia
class Usuario {
    - nome: String
    - classificacaoEtaria : Integer
    - infantil : Bool
    - MinhaLista: midia[]
    - Usuario Usuario(String nome, Integer classificacaoEtaria)
    + void setNome(String nome)
    + void setClassificacaoEtaria(Int classificacaoEtaria)
    + void inserirNaMinhaLista (Midia midia)
    + Midia selecionarMidia (Midia midia)
}

class Midia {
    - video: byte[]
    - título: String
    - genero : Genero
    - estado : Estado
    + Midia Midia(byte[] video, Genero genero)
    + void setVideo(byte[] video)
    + void setTitulo(String string)
    + void setGenero(Genero genero)
    + Midia play(byte[] video, Estado estado)
    + Midia pause(byte[] video, Estado estado)
}

enum Genero {
    ACAO, AVENTURA, CLASSICOS, CULT, COMEDIA, ROMANCE,
    SCI-FI, FANTASIA, SUSPENSE, ANIME, FAMILIA, MUSICA
}

enum Estado {
    NAO-INICIADO, ANDAMENTO, FINALIZADO
}

Usuario -- Midia
Midia -- Genero
Midia -- Estado

@enduml