@startuml Series/Filmes

class Usuario {
    - nome: String
    - classificacaoEtaria : Integer
    - infantil : Bool
    - Usuario Usuario(String nome, Integer classificacaoEtaria)
    + void setNome(String nome)
    + void setClassificacaoEtaria(Int classificacaoEtaria)
    + Secao navegarParaBombando (SecaoBombando secao)
}


class SecaoBombando {
    - colecaoMidias: HashMap<Integer, Midia>()
    + HashMap<Integer, Midia> listarMidiasRelevantes(HashMap<Integer, Midia> colecaoMidias)

}

class Midia {
    - video: byte[]
    - título: String
    - genero : Genero
    - visualizacoes : Int
    - reacoes : Int
    - relevancia : Int
    - publicoInfantil : Bool
    + Midia Midia(byte[] video, Genero genero)
    + void setVideo(byte[] video)
    + void setTitulo(String string)
    + void setGenero(Genero genero)
    + Int calcularRelevancia (Int visualizacoes, Int reacoes, Bool publicoInfantil)
}

enum Genero {
    ACAO, AVENTURA, CLASSICOS, CULT, COMEDIA, ROMANCE,
    SCI-FI, FANTASIA, SUSPENSE, ANIME, FAMILIA, MUSICA
}

Usuario -- SecaoBombando
SecaoBombando -- Midia
Midia -- Genero


@enduml