@startuml Series/Filmes

class Usuario {
    - nome: String
    - classificacaoEtaria : Integer
    - infantil : Bool
    - MinhaLista: midia[]
    - Usuario Usuario(String nome, Integer classificacaoEtaria)
    + void setNome(String nome)
    + void setClassificacaoEtaria(Int classificacaoEtaria)
    + void inserirNaMinhaLista (Midia midia)
    + Midia mostrarMinhaLista (minhaLista [] midia)
}

class Midia {
    - video: byte[]
    - título: String
    - genero : Genero
    + Midia Midia(byte[] video, Genero genero)
    + void setVideo(byte[] video)
    + void setTitulo(String string)
    + void setGenero(Genero genero)
}

enum Genero {
    ACAO, AVENTURA, CLASSICOS, CULT, COMEDIA, ROMANCE,
    SCI-FI, FANTASIA, SUSPENSE, ANIME, FAMILIA, MUSICA
}

Usuario -- Midia
Midia -- Genero


@enduml