@startuml series/filmes
object objUsuario {
    nome = fulano
    classificaoEtaria = 18
    infantil = false
    midiasFavoritas = Midia[]
}
objSecao -- objUsuario

object objSecao {
    colecaoMidias = HashMap<Integer, Midia>()
}

object objMidiaAcao {
    genero = Ação
    titulo = titulo
}
objMidiaAcao -- objSecao 

object objMidiaAventura {
    genero = Aventura
    titulo = titulo
}
objMidiaAventura -- objSecao

object objMidiaComedia {
    genero = Comedia
    titulo = titulo
}
objMidiaComedia -- objSecao


object objMidiaRomance {
    genero = Romance
    titulo = titulo
}
objMidiaRomance  -- objSecao

object objMidiaScifi {
    genero = SciFi
    titulo = titulo
}
objMidiaScifi -- objSecao

object objMidiaSuspense {
    genero = Suspense
    titulo = titulo
}
objMidiaSuspense -- objSecao

object objMidiaAnime {
    genero = Anime
    titulo = titulo
}
objMidiaAnime -- objSecao

@enduml