@startuml lembrete
object ObjLembreteBot{
    imagem = Sino 
    lista = [[0,valor1],[0,valor2],[0,valor3]]
}

object ObjListaLemb{
    lembrete = [[0,valor1],[0,valor2],[0,valor3]]
}

object ObjMidiaCont{
    Midia Midia (video, COMEDIA)
    titulo = titulo do Conteudo
}

object ObjUsuario{
    nome = fulano
    classificacaoEtaria = 18
    infatil = false 
    midiasFavoritas = Midia[]
}

ObjUsuario -- ObjLembreteBot
ObjLembreteBot -- ObjListaLemb
ObjListaLemb  --  ObjMidiaCont
@startuml