@startuml GerenciarPerfis
state fork1 <<fork>>
state join2 <<join>>

[*] --> ConsultandoConta : informarEmailDoUsuario

state ConsultandoConta {
    state ConsultandoConta : do/consultarConta()
}

state RegistrandoConta {
    state RegistrandoConta : do/cadastrarEmail()
    state RegistrandoConta : do/cadastrarSenha()
    state RegistrandoConta : do/cadastrarFormaPagamento()
    state RegistrandoConta : do/validarRecaptcha()
}

ConsultandoConta --> RegistrandoConta : Ainda não cadastrado
RegistrandoConta --> ConsultandoConta : Cadastro finalizado

ConsultandoConta --> RecebendoSenha : contaVálida

state RecebendoSenha {
    state RecebendoSenha : do/inserirSenha()
}

RecebendoSenha --> ValidandoSenha : senhaInformada

state ValidandoSenha {
    state ValidandoSenha : do/validarSenha()
}

ValidandoSenha --> GerenciandoPerfis : senhaCorreta

state GerenciandoPerfis {
    state GerenciandoPerfis : do/adicionarPerfis()
    state GerenciandoPerfis : do/listarPerfis()
}

state EditarPerfil {
    state EditarPerfil : do/alterarNome()
    state EditarPerfil : do/selecionarIdioma()
    state EditarPerfil : do/configurarInicioAutomatico()
    state EditarPerfil : do/alterarClassificacaoEtaria()
}

state AcessarPerfil {

}

GerenciandoPerfis --> fork1
fork1 --> EditarPerfil
fork1 --> AcessarPerfil
EditarPerfil --> join2
AcessarPerfil --> join2
join2 --> ConsultandoConteudo

state ConsultandoConteudo {
    state ConsultandoConteudo : do/listarConteudo()
}

ConsultandoConteudo --> [*]

@enduml

