@startuml aaa
actor Sistema
actor Usuario

Usuario -- (Consultar histórico de estoque)
Sistema -- (Exibir histórico de estoque)
(Consultar histórico de estoque) ..> (Exibir histórico de estoque) :include
(Exibir histórico de estoque) <.. (Por dia) :Extends
(Exibir histórico de estoque) <.. (Por mês) :Extends
(Exibir histórico de estoque) <.. (Por ano) :Extends

@enduml