@startuml usuario
left to right direction
:Usuário geral: as Usuario

Usuario -|> :Usuário não cadastrado:

Usuario --> (Acessar midias)
Usuario --> (Realizar login)
(Acessar midias) ..> (Filtrar por perfil) :includes

:Usuário não cadastrado: --> (Acessar prévias)
:Usuário não cadastrado: --> (Realizar cadastro)
@enduml
