@startuml funcionalidades do menu

activate Usuario
Usuario -> InterfaceUsuario : Abrir
activate InterfaceUsuario
InterfaceUsuario -> Negocio : parent.Presentation(JabberPointApplication.getFileManager().load(TESTFILE))
activate Negocio
Negocio --> InterfaceUsuario : apresentação teste.xml carregada
deactivate Negocio
deactivate InterfaceUsuario
deactivate Usuario

@enduml