@startuml iniciar apresentação
activate Usuario
Usuario -> InterfaceUsuario : run()
activate InterfaceUsuario
InterfaceUsuario -> Negocio
deactivate InterfaceUsuario

activate Negocio
Negocio -> Negocio : Style.createStyles()
Negocio -> Negocio : Acessor.getDemoAcessor.loadFile(presentation, " ")
Negocio -> Negocio : slide.setTitle(title)
Negocio -> Negocio : slide.append(level, message)
Negocio -> Negocio : presentation.append(slide)
Negocio -> Negocio : presentation.setSlideNumber(0)
deactivate Negocio

activate InterfaceUsuario
Negocio --> InterfaceUsuario : apresentação demo
deactivate InterfaceUsuario
deactivate Usuario
@enduml