@startuml prox slide

activate Usuario
Usuario -> InterfaceUsuario : Próximo
activate InterfaceUsuario
InterfaceUsuario -> Negocio : Presentation.nextSlide()
activate Negocio
Negocio --> InterfaceUsuario : setSlideNumber(currentSlideNumber + 1)
deactivate Negocio
deactivate InterfaceUsuario
deactivate Usuario

@enduml