@startuml pular para

activate Usuario
Usuario -> InterfaceUsuario : Pular para
activate InterfaceUsuario
InterfaceUsuario -> Negocio : Presentation.setCurrentSlideNumber()
deactivate InterfaceUsuario
activate Negocio
Negocio -> Negocio : slideViewer.update(presentation.getCurrentSlide(), presentation.currentStatus())
Negocio -> Negocio : repaint()
deactivate Negocio
activate InterfaceUsuario
Negocio --> InterfaceUsuario : Slide alterado
deactivate InterfaceUsuario
deactivate Usuario

@enduml