@startuml implantacao sistema de tickets

node InterfaceJogo as "Tela do jogo \n <<device>>" {
[PaginaJogo]
}

node ServidorFirewall as "Servidor de firewall \n <<device>>" {
[Firewall]
}

node ServidorComunicacao as "Servidor de comunicação \n <<device>>" {
[ControladorJogadas]
}

node ServidorAplicacao as "Servidor de aplicação \n <<device>>" {
[GerenciadorTabuleiro]
[GerenciadorCartas]
[GerenciadorPontuacao]
}

node ServidorBancoDados as "Servidor de banco de dados \n <<device>>"{
[SGBD]
}

InterfaceJogo - ServidorFirewall : <TCP/IP>
ServidorFirewall - ServidorComunicacao : <TCP/IP>
ServidorComunicacao -- ServidorAplicacao : <TCP/IP>
ServidorAplicacao -- ServidorBancoDados : <TCP/IP>
@enduml