@startuml sequence jogo da memoria
actor Usuario

Usuario -> InterfaceUsuario : iniciarJogo()

InterfaceUsuario -> Negocio: renderizarTabuleiro()
Negocio -> Repositorio: obterCartasEmbaralhadas()
Repositorio --> Negocio: cartas do mesmo grupo lógico
Negocio --> InterfaceUsuario : tabuleiro

InterfaceUsuario --> Usuario

Usuario -> InterfaceUsuario : selecionarCartas()
InterfaceUsuario -> Negocio: virarCartas()
Negocio -> Negocio : verificarCartas()
Negocio -> Repositorio: atribuirPontuacao()
Repositorio --> Negocio: pontuacao
Negocio --> InterfaceUsuario : tabuleiro atualizado

InterfaceUsuario --> Usuario

@enduml
