@startuml package geral
package GerenciamentoPerfil {
    class Usuario {}
    enum TipoUsuario {}
    Usuario -- TipoUsuario
}

package GerenciamentoSecoes {
    class Secao {}
}

package GerenciamentoMidia {
    class Midia {}
    enum Estado {}
    enum Genero {}  
    Midia -- Estado
    Midia -- Genero
}

GerenciamentoPerfil - GerenciamentoSecoes
GerenciamentoSecoes - GerenciamentoMidia

@enduml