@startuml Secoes

class SecaoMidia {
    - colecaoMidias: HashMap<Integer, Midia>()
    + void ordenarMidiasAz(HashMap<Integer, Midia> colecaoMidias)
    + void ordenarMidiasZa(HashMap<Integer, Midia> colecaoMidias)
    + void ordenarMidiasEstreia(HashMap<Integer, Midia> colecaoMidias)
    + HashMap<Integer, Midia> listarMidias(HashMap<Integer, Midia> colecaoMidias)
}

class SecaoInfantil {
    - colecaoMidias: HashMap<Integer, MidiaInfantil>
    + HashMap<Integer, Midia> listarConteudoInfantil(HashMap<Integer, Midia> colecaoMidias)
}

SecaoMidia <|-- SecaoInfantil

@enduml