@startuml slide viewer component
class JComponent{}

JComponent <|-- SlideViewer

class SlideViewer{
    - static final Color BGCOLOR = Color.white
    - static final Color COLOR = Color.black
    - static final String FONTNAME = "Dialog"
    - static final int FONTSTYLE = Font.BOLD
    - static final int FONTHEIGHT = 10
    - static final int XPOS = 1100
    - static final int YPOS = 20
    - Slide slide
    - String status
    - Font labelFont = null

    + SlideViewer SlideViewer()
    + void update()
    + void paintComponnent()
    + Dimension getPreferredSize()
}
@enduml