@startuml Selecionar mídia
actor Usuario
actor Sistema 
(Usuario) --> (Selecionar midia)
(Selecionar midia) <.. (Assistir mídia) :Extends
(Selecionar midia) <.. (Adicionar à lista) :Extends
(Selecionar midia) <.. (Classificar mídia) :Extends
(Selecionar midia) <.. (Remover da fileira) :Extends
(Selecionar midia) <.. (Ver informações) :Extends

(Sistema) --> (Carregar informações)
(Sistema) --> (Salvar alterações)

(Selecionar midia) ..> (Salvar alterações) : Include
(Ver informações) ..> (Carregar informações) :Include

@enduml