@startuml strategy nos tipos de arquivos

class JabberPointApplication {
    
}

JabberPointApplication -- FileManager
FileManager *-- IFilePresentationFormat

class FileManager {
    - String path
    - IFilePresentationFormat file

    + FileManager(String path)
    + void getFileFormat()
}

FileManager - FactoryFile

class FactoryFile {
    - String extension
    + FactoryFile(String extension)
    + IFilePresentationFormat getFile()
}

interface IFilePresentationFormat {
    + Presentation load(String fileName);
    + void save(Presentation presentation, String fileName);
}

class XMLFormat implements IFilePresentationFormat {
    + Presentation load(String fileName);
    + void save(Presentation presentation, String fileName);
}

class HTMLFormat implements IFilePresentationFormat {
    + Presentation load(String fileName);
    + void save(Presentation presentation, String fileName);
}

class JSONFormat {
    + Presentation load(String fileName);
    + void save(Presentation presentation, String fileName);
}

JSONFormat .|> IFilePresentationFormat

@enduml