@startuml html format

    class HTMLFormat implements IFilePresentationFormat {
        + Presentation load(String filename)
        + void save(Presentation presentation, String filename)
    }

@enduml