@startuml usuario
left to right direction
:Usuário geral: as Usuario
Usuario -|> :Usuário não cadastrado:

Usuario --> (Acessar mídias)
Usuario --> (Acessar conta)
(Acessar mídias) ..> (Filtrar por perfil) :includes

:Usuário não cadastrado: --> (Acessar prévias)
:Usuário não cadastrado: --> (Cadastrar conta)
@enduml
