@startuml style
    class Style {
        - static Style[] styles
        - static final String FONTNAME = "Helvetica"
        + int indent
        + Color color
        + Font font 
        + int fontSize
        + int leading

        + static void createStyles()
        + static Style getStyle(int level)
        + Style Style(int indent, Color color, int points, int leading)
        + String toString()
        + Font getFont(float scale)
    }
@enduml