@startuml XML acessor
    class XMLAccessor{
        # static final String DEFAULT_API_TO_USE = "dom"
        # static final String SHOWTITLE = "showtitle"
        # static final String SLIDETITTLE = "slidetittle"
        # static final String SLIDE = "slide"
        # static final String ITEM = "item"
        # static final String LEVEL = "level"
        # static final String KIND = "kind"
        # static final String TEXT = "text"
        # static final String IMAGE = "image"
        # static final String PCE = "Parser Configuration Exception"
        # static final String UKNOWNTYPE = "Unknown Element type"
        # static final String NFE = "Number Format Exception"

        - String getTitle(Element element, String tagName)
        + void loadFile(Presentation presentation, String filename)
        # void loadSlideItem(Slide slide, Element item)
        + void saveFile(Presentation presentation, String filename)
    }
@enduml