@startuml accessor
abstract class Accessor {
    + final String DEMO_NAME = "Apresentação de demonstração"
    + final String DEFAULT_EXTENSION = ".xml"
    + static Accessor getDemoAccessor()
    + Accessor Accessor()
    + abstract void loadFile(Presentation presentation, String fileName)
    + abstract void saveFile(Presentation presentation, String fileName)
}
@enduml