@startuml menu controller
    class MenuBar {}

    MenuBar <|-- MenuController

    class MenuController {
        - static final long serialVersionUID = 227L
        - Frame parent
        - Presentation presentation
        # static final String FILE = "Arquivo"
        # static final String EXIT = "Sair"
        # static final String HELP = "Ajuda"
        # static final String NEW = "Novo"
        # static final String NEXT = "Próximo"
        # static final String OPEN = "Abrir"
        # static final String SAVE = "Salvar"
        # static final String VIEW = "Sobre"

        + MenuController MenuController(Frame frame, Presentation presentation)
        + MenuItem mkMenuItem(String name)
    }
@enduml