@startuml menu controller
    class MenuBar {}

    MenuBar <|-- MenuController

class MenuController {

  - {static} serialVersionUID : Long = 227L
  - parent : Frame
  - presentation : Presentation

  # {static} ABOUT : String = "Sobre"
  # {static} FILE : String = "Arquivo"
  # {static} EXIT : String = "Sair"
  # {static} GOTO : String = "Pular para"
  # {static} HELP : String = "Ajuda"
  # {static} NEW : String = "Novo"
  # {static} NEXT : String = "Próximo"
  # {static} OPEN : String = "Abrir"
  # {static} PAGENR : String = "Número do Slide"
  # {static} PREV : String = "Anterior"
  # {static} SAVE : String = "Salvar"
  # {static} VIEW : String = "Visualizar"

  # {static} TESTFILE : String = "classpath:test.xml"
  # {static} SAVEFILE : String = "classpath:dump.xml"

  # {static} IOEX : String = "IO Exception: "
  # {static} LOADERR : String = "Erro ao carregar"
  # {static} SAVERR : String = "Erro ao salvar"

  + MenuController(frame : Frame, pres : Presentation)
  + mkMenuItem(name : String) : MenuItem

}

@enduml