@startuml presentation
    class Presentation {
        - String title
        - ArrayList<Slide> showList = null
        - int currenteSlideNumber

        + Presentation Presentation()
        + int getSize()
        + String getTitle()
        + void setTitle()
        + int getSlideNumber()
        + void setSlideNumber(int number)
        + void prevSlide()
        + void nextSlide()
        + void clear()
        + void append(Slide slide)
        + Slide getSlide(int number)
        + Slide getCurrentSlide()
    }
@enduml