@startuml presentation
    class Presentation {
        - String title
        - ArrayList<Slide> showList = null

        + Presentation Presentation()
        + String getTitle()
        + void setTitle()
        + int getSlideNumber()
        + void setSlideNumber(int number)
        + void prevSlide()
        + void nextSlide()
        + void clear()
        + void append(Slide slide)
        + Slide getSlide(int number)
        + void exit()
    }
@enduml