@startuml slide
class Slide {
    # SlideItem title
    # Vector<SlideItem> items

    + Slide Slide()
    + void append(SlideItem anItem)
    + String getTitle()
    + void setTitle(String newTitle)
    + void appendSlideItem(SlideItem anItem)
    + void appendTextItem(int level, String message)
    + SlideItem getSlideItem(int number)
    + Vector<SlideItem> getSlideItems()
    + getSize()
}
@enduml