@startuml slide
class Slide {
    # SlideItem title
    # Vector<SlideItem> items

    + Slide Slide()
    + void appendSlideItem(SlideItem anItem)
    + String getTitleText()
    + TextItem getTitle()
    + void setTitle()
    + void appendTextItem(int level, String message)
    + SlideItem getSlideItem(int number)
    + Vector<SlideItem> getSlideItems()
    + int getSize()
}
@enduml