@startuml text item
    class TextItem {
        - String text
        - static final String EMPTYTEXT = "No Text Given"
        + TextItem TextItem(int level, String string)
        + TextItem TextItem()
        + String getText()
        + AtributtedString getAtributtedString(Style style, float scale)
        + Rectangle getBoundingBox(Graphics g, ImageObserver observer, float scale, Style myStyle) 
        + void Draw(int x, int y, float scale, Graphics g, Style myStyle, ImageObserver o)
        - List<TextLayout> getLayouts(Graphics g, Style s, float scale)
        + String toString()
    }
@enduml